[package]
name = "dark-star-controller"
version = "0.1.0"
edition = "2021"

[[ bin ]]
name = "dstrc"
path = "src/main.rs"

[dependencies]
sysinfo = "0.30"
chrono = { version = "0.4", features = ["serde"] }
gethostname = "0.4.3"
nix = "0.24.1"
systemstat = "0.2.3"
netstat2 = "0.9"
